export type JerseyStyle = 'classic' | 'stripe' | 'heritage';
export type HelmetStyle = 'shell' | 'cage' | 'visor';
export type CosmeticKind = 'jerseyStyle' | 'jerseyColor' | 'helmetStyle' | 'helmetColor' | 'gloveColor' | 'stickStyle';
export type PlayerProfile = { version: 1; name: string; jerseyNumber: number; jerseyStyle: JerseyStyle; jerseyColor: string; helmetStyle: HelmetStyle; helmetColor: string; gloveColor: string; stickStyle: string };
export type Cosmetic = { id: string; label: string; color?: string; kind: CosmeticKind; requirement?: CosmeticRequirement };
export type CosmeticRequirement = { type: 'stars' | 'chapter' | 'achievement' | 'perfectChapter' | 'shop'; value: number | string; text: string };
export const COSMETICS: readonly Cosmetic[] = [
  { id:'classic', label:'Classic', kind:'jerseyStyle' }, { id:'stripe', label:'Stripe', kind:'jerseyStyle', requirement:{type:'stars',value:8,text:'Earn 8 total stars'} }, { id:'heritage', label:'Heritage', kind:'jerseyStyle', requirement:{type:'perfectChapter',value:0,text:'3-star First Tracks'} },
  { id:'hero-teal', label:'Hero Teal', color:'#18DCB6', kind:'jerseyColor' }, { id:'ice', label:'Ice White', color:'#F4FAFF', kind:'jerseyColor' }, { id:'ember', label:'Ember Red', color:'#D94A4A', kind:'jerseyColor', requirement:{type:'chapter',value:1,text:'Complete Heat Check'} }, { id:'gold', label:'Gold Rush', color:'#E7B84B', kind:'jerseyColor', requirement:{type:'achievement',value:'bar-down',text:'Unlock the Bar Down achievement'} },
  { id:'shell', label:'Shell', kind:'helmetStyle' }, { id:'cage', label:'Cage', kind:'helmetStyle', requirement:{type:'stars',value:12,text:'Earn 12 total stars'} }, { id:'visor', label:'Visor', kind:'helmetStyle', requirement:{type:'perfectChapter',value:1,text:'3-star Heat Check'} },
  { id:'white', label:'White', color:'#FFFFFF', kind:'helmetColor' }, { id:'navy', label:'Navy', color:'#172A46', kind:'helmetColor', requirement:{type:'chapter',value:2,text:'Complete Playmakers'} },
  { id:'black', label:'Black', color:'#17191D', kind:'gloveColor' }, { id:'teal', label:'Teal', color:'#35C6C2', kind:'gloveColor', requirement:{type:'stars',value:18,text:'Earn 18 total stars'} },
  { id:'wood', label:'Wood', kind:'stickStyle' }, { id:'carbon', label:'Carbon', kind:'stickStyle', requirement:{type:'achievement',value:'no-retry',text:'Unlock the No Retry achievement'} },
  { id:'neon', label:'Neon Ice', color:'#69F5FF', kind:'jerseyColor', requirement:{type:'shop',value:'neon',text:'Purchase in the Shop'} },
  { id:'midnight', label:'Midnight', color:'#4C5B8E', kind:'helmetColor', requirement:{type:'shop',value:'midnight',text:'Purchase in the Shop'} },
  { id:'shop-gold', label:'Gold', color:'#E7B84B', kind:'gloveColor', requirement:{type:'shop',value:'shop-gold',text:'Purchase in the Shop'} },
  { id:'pro-carbon', label:'Pro Carbon', kind:'stickStyle', requirement:{type:'shop',value:'pro-carbon',text:'Purchase in the Shop'} },
];
const find = (kind: CosmeticKind, id: string) => COSMETICS.find(c => c.kind===kind && c.id===id);
export const defaultProfile = (): PlayerProfile => ({version:1,name:'Player',jerseyNumber:9,jerseyStyle:'classic',jerseyColor:'hero-teal',helmetStyle:'shell',helmetColor:'white',gloveColor:'black',stickStyle:'wood'});
const str=(v:unknown,f:string)=>typeof v==='string'&&v.trim()?v:f;
export function sanitizeProfile(input: Partial<PlayerProfile>|null|undefined): PlayerProfile { const d=defaultProfile(); const x=input||{}; const pick=(k:CosmeticKind, v:unknown, fallback:string)=>typeof v==='string'&&find(k,v)?v as string:fallback; return {version:1,name:str(x.name,d.name).slice(0,24),jerseyNumber:Number.isInteger(x.jerseyNumber)&&Number(x.jerseyNumber)>=0&&Number(x.jerseyNumber)<=99?Number(x.jerseyNumber):d.jerseyNumber,jerseyStyle:pick('jerseyStyle',x.jerseyStyle,d.jerseyStyle) as JerseyStyle,jerseyColor:pick('jerseyColor',x.jerseyColor,d.jerseyColor),helmetStyle:pick('helmetStyle',x.helmetStyle,d.helmetStyle) as HelmetStyle,helmetColor:pick('helmetColor',x.helmetColor,d.helmetColor),gloveColor:pick('gloveColor',x.gloveColor,d.gloveColor),stickStyle:pick('stickStyle',x.stickStyle,d.stickStyle)}; }
export function parseProfile(raw:string|null):PlayerProfile { if(!raw)return defaultProfile(); try { const v=JSON.parse(raw); return sanitizeProfile(v?.profile??v); } catch { return defaultProfile(); } }
export function isCosmeticUnlocked(c:Cosmetic, stats:{totalStars?:number;completedChapters?:Set<number>|number[];achievements?:Set<string>|Record<string,boolean>;perfectChapters?:Set<number>|number[];shopOwned?:Set<string>|string[]}={}):boolean { if(!c.requirement)return true; const r=c.requirement; if(r.type==='stars')return (stats.totalStars||0)>=Number(r.value); const has=(v:Set<any>|any[]|undefined,n:any)=>v instanceof Set?v.has(n):Array.isArray(v)&&v.includes(n); if(r.type==='chapter')return has(stats.completedChapters,Number(r.value)); if(r.type==='perfectChapter')return has(stats.perfectChapters,Number(r.value)); if(r.type==='shop')return has(stats.shopOwned,String(r.value)); return stats.achievements instanceof Set?stats.achievements.has(String(r.value)):!!stats.achievements?.[String(r.value)]; }
export const cosmeticStatus=(id:string,stats:any)=>{const c=COSMETICS.find(x=>x.id===id); return c?{cosmetic:c,unlocked:isCosmeticUnlocked(c,stats),requirement:c.requirement?.text}:{cosmetic:undefined,unlocked:false,requirement:'Unknown cosmetic'};};
export function updateProfile(p:PlayerProfile, patch:Partial<PlayerProfile>):PlayerProfile{return sanitizeProfile({...p,...patch});}
